apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-iac-perception
  namespace: sdi-ros-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-iac-perception
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: conf-macvlan-eth0
      labels:
        app: ros-iac-perception
        role: sdi-apps
    spec:
      containers:
      - image: jsseok/ros-iac-apps:seg
        imagePullPolicy: Always
        tty: true
        name: ros-iac-perception
      nodeSelector:
        kubernetes.io/hostname: node2-desktop
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-iac-broker
  namespace: sdi-ros-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-iac-broker
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: conf-macvlan-eth0
      labels:
        app: ros-iac-broker
        role: sdi-apps
    spec:
      containers:
      - image: jsseok/ros-iac-apps:broker
        imagePullPolicy: Always
        tty: true
        name: ros-iac-broker
      nodeSelector:
        kubernetes.io/hostname: node1-desktop
      restartPolicy: Always
