apiVersion: apps/v1
kind: Deployment
metadata:
  name: perception
  namespace: sdi-ros-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perception
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: conf-macvlan-eth0
      labels:
        app: perception
    spec:
      containers:
      - image: jsseok/ros-iac-apps:seg
        name: perception

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: sdi-ros-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: conf-macvlan-eth0
      labels:
        app: broker
    spec:
      containers:
      - image: jsseok/ros-iac-apps:broker
        name: broker
